// Generated by Wrangler on Sun Sep 15 2024 21:12:39 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	cloudflare_KV: KVNamespace;
	USER_SESSION_SECRET: "testing123";
	USER_COOKIE_SECRET: "testing123";
	JWT_SECRET_KEY: "happy";
	cloudflare_db: D1Database;
}
