// Generated by Wrangler on Tue Sep 03 2024 13:48:41 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	cloudflare_KV: KVNamespace;
	USER_SESSION_SECRET: "testing123";
	USER_COOKIE_SECRET: "testing123";
	cloudflare_db: D1Database;
}
