# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI.models.branded_food_item_label_nutrients_calcium import BrandedFoodItemLabelNutrientsCalcium  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_calories import BrandedFoodItemLabelNutrientsCalories  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_carbohydrates import BrandedFoodItemLabelNutrientsCarbohydrates  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_fat import BrandedFoodItemLabelNutrientsFat  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_fiber import BrandedFoodItemLabelNutrientsFiber  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_iron import BrandedFoodItemLabelNutrientsIron  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_potassium import BrandedFoodItemLabelNutrientsPotassium  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_protein import BrandedFoodItemLabelNutrientsProtein  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_saturated_fat import BrandedFoodItemLabelNutrientsSaturatedFat  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_sugars import BrandedFoodItemLabelNutrientsSugars  # noqa: F401,E501
from FoodCentralAPI.models.branded_food_item_label_nutrients_trans_fat import BrandedFoodItemLabelNutrientsTransFat  # noqa: F401,E501
from FoodCentralAPI import util


class BrandedFoodItemLabelNutrients(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, fat: BrandedFoodItemLabelNutrientsFat=None, saturated_fat: BrandedFoodItemLabelNutrientsSaturatedFat=None, trans_fat: BrandedFoodItemLabelNutrientsTransFat=None, cholesterol: BrandedFoodItemLabelNutrientsTransFat=None, sodium: BrandedFoodItemLabelNutrientsTransFat=None, carbohydrates: BrandedFoodItemLabelNutrientsCarbohydrates=None, fiber: BrandedFoodItemLabelNutrientsFiber=None, sugars: BrandedFoodItemLabelNutrientsSugars=None, protein: BrandedFoodItemLabelNutrientsProtein=None, calcium: BrandedFoodItemLabelNutrientsCalcium=None, iron: BrandedFoodItemLabelNutrientsIron=None, potassium: BrandedFoodItemLabelNutrientsPotassium=None, calories: BrandedFoodItemLabelNutrientsCalories=None):  # noqa: E501
        """BrandedFoodItemLabelNutrients - a model defined in Swagger

        :param fat: The fat of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type fat: BrandedFoodItemLabelNutrientsFat
        :param saturated_fat: The saturated_fat of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type saturated_fat: BrandedFoodItemLabelNutrientsSaturatedFat
        :param trans_fat: The trans_fat of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type trans_fat: BrandedFoodItemLabelNutrientsTransFat
        :param cholesterol: The cholesterol of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type cholesterol: BrandedFoodItemLabelNutrientsTransFat
        :param sodium: The sodium of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type sodium: BrandedFoodItemLabelNutrientsTransFat
        :param carbohydrates: The carbohydrates of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type carbohydrates: BrandedFoodItemLabelNutrientsCarbohydrates
        :param fiber: The fiber of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type fiber: BrandedFoodItemLabelNutrientsFiber
        :param sugars: The sugars of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type sugars: BrandedFoodItemLabelNutrientsSugars
        :param protein: The protein of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type protein: BrandedFoodItemLabelNutrientsProtein
        :param calcium: The calcium of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type calcium: BrandedFoodItemLabelNutrientsCalcium
        :param iron: The iron of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type iron: BrandedFoodItemLabelNutrientsIron
        :param potassium: The potassium of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type potassium: BrandedFoodItemLabelNutrientsPotassium
        :param calories: The calories of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :type calories: BrandedFoodItemLabelNutrientsCalories
        """
        self.swagger_types = {
            'fat': BrandedFoodItemLabelNutrientsFat,
            'saturated_fat': BrandedFoodItemLabelNutrientsSaturatedFat,
            'trans_fat': BrandedFoodItemLabelNutrientsTransFat,
            'cholesterol': BrandedFoodItemLabelNutrientsTransFat,
            'sodium': BrandedFoodItemLabelNutrientsTransFat,
            'carbohydrates': BrandedFoodItemLabelNutrientsCarbohydrates,
            'fiber': BrandedFoodItemLabelNutrientsFiber,
            'sugars': BrandedFoodItemLabelNutrientsSugars,
            'protein': BrandedFoodItemLabelNutrientsProtein,
            'calcium': BrandedFoodItemLabelNutrientsCalcium,
            'iron': BrandedFoodItemLabelNutrientsIron,
            'potassium': BrandedFoodItemLabelNutrientsPotassium,
            'calories': BrandedFoodItemLabelNutrientsCalories
        }

        self.attribute_map = {
            'fat': 'fat',
            'saturated_fat': 'saturatedFat',
            'trans_fat': 'transFat',
            'cholesterol': 'cholesterol',
            'sodium': 'sodium',
            'carbohydrates': 'carbohydrates',
            'fiber': 'fiber',
            'sugars': 'sugars',
            'protein': 'protein',
            'calcium': 'calcium',
            'iron': 'iron',
            'potassium': 'potassium',
            'calories': 'calories'
        }
        self._fat = fat
        self._saturated_fat = saturated_fat
        self._trans_fat = trans_fat
        self._cholesterol = cholesterol
        self._sodium = sodium
        self._carbohydrates = carbohydrates
        self._fiber = fiber
        self._sugars = sugars
        self._protein = protein
        self._calcium = calcium
        self._iron = iron
        self._potassium = potassium
        self._calories = calories

    @classmethod
    def from_dict(cls, dikt) -> 'BrandedFoodItemLabelNutrients':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BrandedFoodItem_labelNutrients of this BrandedFoodItemLabelNutrients.  # noqa: E501
        :rtype: BrandedFoodItemLabelNutrients
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fat(self) -> BrandedFoodItemLabelNutrientsFat:
        """Gets the fat of this BrandedFoodItemLabelNutrients.


        :return: The fat of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsFat
        """
        return self._fat

    @fat.setter
    def fat(self, fat: BrandedFoodItemLabelNutrientsFat):
        """Sets the fat of this BrandedFoodItemLabelNutrients.


        :param fat: The fat of this BrandedFoodItemLabelNutrients.
        :type fat: BrandedFoodItemLabelNutrientsFat
        """

        self._fat = fat

    @property
    def saturated_fat(self) -> BrandedFoodItemLabelNutrientsSaturatedFat:
        """Gets the saturated_fat of this BrandedFoodItemLabelNutrients.


        :return: The saturated_fat of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsSaturatedFat
        """
        return self._saturated_fat

    @saturated_fat.setter
    def saturated_fat(self, saturated_fat: BrandedFoodItemLabelNutrientsSaturatedFat):
        """Sets the saturated_fat of this BrandedFoodItemLabelNutrients.


        :param saturated_fat: The saturated_fat of this BrandedFoodItemLabelNutrients.
        :type saturated_fat: BrandedFoodItemLabelNutrientsSaturatedFat
        """

        self._saturated_fat = saturated_fat

    @property
    def trans_fat(self) -> BrandedFoodItemLabelNutrientsTransFat:
        """Gets the trans_fat of this BrandedFoodItemLabelNutrients.


        :return: The trans_fat of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsTransFat
        """
        return self._trans_fat

    @trans_fat.setter
    def trans_fat(self, trans_fat: BrandedFoodItemLabelNutrientsTransFat):
        """Sets the trans_fat of this BrandedFoodItemLabelNutrients.


        :param trans_fat: The trans_fat of this BrandedFoodItemLabelNutrients.
        :type trans_fat: BrandedFoodItemLabelNutrientsTransFat
        """

        self._trans_fat = trans_fat

    @property
    def cholesterol(self) -> BrandedFoodItemLabelNutrientsTransFat:
        """Gets the cholesterol of this BrandedFoodItemLabelNutrients.


        :return: The cholesterol of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsTransFat
        """
        return self._cholesterol

    @cholesterol.setter
    def cholesterol(self, cholesterol: BrandedFoodItemLabelNutrientsTransFat):
        """Sets the cholesterol of this BrandedFoodItemLabelNutrients.


        :param cholesterol: The cholesterol of this BrandedFoodItemLabelNutrients.
        :type cholesterol: BrandedFoodItemLabelNutrientsTransFat
        """

        self._cholesterol = cholesterol

    @property
    def sodium(self) -> BrandedFoodItemLabelNutrientsTransFat:
        """Gets the sodium of this BrandedFoodItemLabelNutrients.


        :return: The sodium of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsTransFat
        """
        return self._sodium

    @sodium.setter
    def sodium(self, sodium: BrandedFoodItemLabelNutrientsTransFat):
        """Sets the sodium of this BrandedFoodItemLabelNutrients.


        :param sodium: The sodium of this BrandedFoodItemLabelNutrients.
        :type sodium: BrandedFoodItemLabelNutrientsTransFat
        """

        self._sodium = sodium

    @property
    def carbohydrates(self) -> BrandedFoodItemLabelNutrientsCarbohydrates:
        """Gets the carbohydrates of this BrandedFoodItemLabelNutrients.


        :return: The carbohydrates of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsCarbohydrates
        """
        return self._carbohydrates

    @carbohydrates.setter
    def carbohydrates(self, carbohydrates: BrandedFoodItemLabelNutrientsCarbohydrates):
        """Sets the carbohydrates of this BrandedFoodItemLabelNutrients.


        :param carbohydrates: The carbohydrates of this BrandedFoodItemLabelNutrients.
        :type carbohydrates: BrandedFoodItemLabelNutrientsCarbohydrates
        """

        self._carbohydrates = carbohydrates

    @property
    def fiber(self) -> BrandedFoodItemLabelNutrientsFiber:
        """Gets the fiber of this BrandedFoodItemLabelNutrients.


        :return: The fiber of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsFiber
        """
        return self._fiber

    @fiber.setter
    def fiber(self, fiber: BrandedFoodItemLabelNutrientsFiber):
        """Sets the fiber of this BrandedFoodItemLabelNutrients.


        :param fiber: The fiber of this BrandedFoodItemLabelNutrients.
        :type fiber: BrandedFoodItemLabelNutrientsFiber
        """

        self._fiber = fiber

    @property
    def sugars(self) -> BrandedFoodItemLabelNutrientsSugars:
        """Gets the sugars of this BrandedFoodItemLabelNutrients.


        :return: The sugars of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsSugars
        """
        return self._sugars

    @sugars.setter
    def sugars(self, sugars: BrandedFoodItemLabelNutrientsSugars):
        """Sets the sugars of this BrandedFoodItemLabelNutrients.


        :param sugars: The sugars of this BrandedFoodItemLabelNutrients.
        :type sugars: BrandedFoodItemLabelNutrientsSugars
        """

        self._sugars = sugars

    @property
    def protein(self) -> BrandedFoodItemLabelNutrientsProtein:
        """Gets the protein of this BrandedFoodItemLabelNutrients.


        :return: The protein of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsProtein
        """
        return self._protein

    @protein.setter
    def protein(self, protein: BrandedFoodItemLabelNutrientsProtein):
        """Sets the protein of this BrandedFoodItemLabelNutrients.


        :param protein: The protein of this BrandedFoodItemLabelNutrients.
        :type protein: BrandedFoodItemLabelNutrientsProtein
        """

        self._protein = protein

    @property
    def calcium(self) -> BrandedFoodItemLabelNutrientsCalcium:
        """Gets the calcium of this BrandedFoodItemLabelNutrients.


        :return: The calcium of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsCalcium
        """
        return self._calcium

    @calcium.setter
    def calcium(self, calcium: BrandedFoodItemLabelNutrientsCalcium):
        """Sets the calcium of this BrandedFoodItemLabelNutrients.


        :param calcium: The calcium of this BrandedFoodItemLabelNutrients.
        :type calcium: BrandedFoodItemLabelNutrientsCalcium
        """

        self._calcium = calcium

    @property
    def iron(self) -> BrandedFoodItemLabelNutrientsIron:
        """Gets the iron of this BrandedFoodItemLabelNutrients.


        :return: The iron of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsIron
        """
        return self._iron

    @iron.setter
    def iron(self, iron: BrandedFoodItemLabelNutrientsIron):
        """Sets the iron of this BrandedFoodItemLabelNutrients.


        :param iron: The iron of this BrandedFoodItemLabelNutrients.
        :type iron: BrandedFoodItemLabelNutrientsIron
        """

        self._iron = iron

    @property
    def potassium(self) -> BrandedFoodItemLabelNutrientsPotassium:
        """Gets the potassium of this BrandedFoodItemLabelNutrients.


        :return: The potassium of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsPotassium
        """
        return self._potassium

    @potassium.setter
    def potassium(self, potassium: BrandedFoodItemLabelNutrientsPotassium):
        """Sets the potassium of this BrandedFoodItemLabelNutrients.


        :param potassium: The potassium of this BrandedFoodItemLabelNutrients.
        :type potassium: BrandedFoodItemLabelNutrientsPotassium
        """

        self._potassium = potassium

    @property
    def calories(self) -> BrandedFoodItemLabelNutrientsCalories:
        """Gets the calories of this BrandedFoodItemLabelNutrients.


        :return: The calories of this BrandedFoodItemLabelNutrients.
        :rtype: BrandedFoodItemLabelNutrientsCalories
        """
        return self._calories

    @calories.setter
    def calories(self, calories: BrandedFoodItemLabelNutrientsCalories):
        """Sets the calories of this BrandedFoodItemLabelNutrients.


        :param calories: The calories of this BrandedFoodItemLabelNutrients.
        :type calories: BrandedFoodItemLabelNutrientsCalories
        """

        self._calories = calories
