# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI import util


class FoodAttributeFoodAttributeType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, description: str=None):  # noqa: E501
        """FoodAttributeFoodAttributeType - a model defined in Swagger

        :param id: The id of this FoodAttributeFoodAttributeType.  # noqa: E501
        :type id: int
        :param name: The name of this FoodAttributeFoodAttributeType.  # noqa: E501
        :type name: str
        :param description: The description of this FoodAttributeFoodAttributeType.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description'
        }
        self._id = id
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'FoodAttributeFoodAttributeType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FoodAttribute_FoodAttributeType of this FoodAttributeFoodAttributeType.  # noqa: E501
        :rtype: FoodAttributeFoodAttributeType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this FoodAttributeFoodAttributeType.


        :return: The id of this FoodAttributeFoodAttributeType.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this FoodAttributeFoodAttributeType.


        :param id: The id of this FoodAttributeFoodAttributeType.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this FoodAttributeFoodAttributeType.


        :return: The name of this FoodAttributeFoodAttributeType.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this FoodAttributeFoodAttributeType.


        :param name: The name of this FoodAttributeFoodAttributeType.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this FoodAttributeFoodAttributeType.


        :return: The description of this FoodAttributeFoodAttributeType.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this FoodAttributeFoodAttributeType.


        :param description: The description of this FoodAttributeFoodAttributeType.
        :type description: str
        """

        self._description = description
