# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI.models.sample_food_item import SampleFoodItem  # noqa: F401,E501
from FoodCentralAPI import util


class InputFoodFoundation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, food_description: str=None, input_food: SampleFoodItem=None):  # noqa: E501
        """InputFoodFoundation - a model defined in Swagger

        :param id: The id of this InputFoodFoundation.  # noqa: E501
        :type id: int
        :param food_description: The food_description of this InputFoodFoundation.  # noqa: E501
        :type food_description: str
        :param input_food: The input_food of this InputFoodFoundation.  # noqa: E501
        :type input_food: SampleFoodItem
        """
        self.swagger_types = {
            'id': int,
            'food_description': str,
            'input_food': SampleFoodItem
        }

        self.attribute_map = {
            'id': 'id',
            'food_description': 'foodDescription',
            'input_food': 'inputFood'
        }
        self._id = id
        self._food_description = food_description
        self._input_food = input_food

    @classmethod
    def from_dict(cls, dikt) -> 'InputFoodFoundation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InputFoodFoundation of this InputFoodFoundation.  # noqa: E501
        :rtype: InputFoodFoundation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InputFoodFoundation.


        :return: The id of this InputFoodFoundation.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InputFoodFoundation.


        :param id: The id of this InputFoodFoundation.
        :type id: int
        """

        self._id = id

    @property
    def food_description(self) -> str:
        """Gets the food_description of this InputFoodFoundation.


        :return: The food_description of this InputFoodFoundation.
        :rtype: str
        """
        return self._food_description

    @food_description.setter
    def food_description(self, food_description: str):
        """Sets the food_description of this InputFoodFoundation.


        :param food_description: The food_description of this InputFoodFoundation.
        :type food_description: str
        """

        self._food_description = food_description

    @property
    def input_food(self) -> SampleFoodItem:
        """Gets the input_food of this InputFoodFoundation.


        :return: The input_food of this InputFoodFoundation.
        :rtype: SampleFoodItem
        """
        return self._input_food

    @input_food.setter
    def input_food(self, input_food: SampleFoodItem):
        """Sets the input_food of this InputFoodFoundation.


        :param input_food: The input_food of this InputFoodFoundation.
        :type input_food: SampleFoodItem
        """

        self._input_food = input_food
