# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI.models.food_attribute import FoodAttribute  # noqa: F401,E501
from FoodCentralAPI.models.food_portion import FoodPortion  # noqa: F401,E501
from FoodCentralAPI.models.input_food_survey import InputFoodSurvey  # noqa: F401,E501
from FoodCentralAPI.models.wweia_food_category import WweiaFoodCategory  # noqa: F401,E501
from FoodCentralAPI import util


class SurveyFoodItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, fdc_id: int=None, datatype: str=None, description: str=None, end_date: str=None, food_class: str=None, food_code: str=None, publication_date: str=None, start_date: str=None, food_attributes: List[FoodAttribute]=None, food_portions: List[FoodPortion]=None, input_foods: List[InputFoodSurvey]=None, wweia_food_category: WweiaFoodCategory=None):  # noqa: E501
        """SurveyFoodItem - a model defined in Swagger

        :param fdc_id: The fdc_id of this SurveyFoodItem.  # noqa: E501
        :type fdc_id: int
        :param datatype: The datatype of this SurveyFoodItem.  # noqa: E501
        :type datatype: str
        :param description: The description of this SurveyFoodItem.  # noqa: E501
        :type description: str
        :param end_date: The end_date of this SurveyFoodItem.  # noqa: E501
        :type end_date: str
        :param food_class: The food_class of this SurveyFoodItem.  # noqa: E501
        :type food_class: str
        :param food_code: The food_code of this SurveyFoodItem.  # noqa: E501
        :type food_code: str
        :param publication_date: The publication_date of this SurveyFoodItem.  # noqa: E501
        :type publication_date: str
        :param start_date: The start_date of this SurveyFoodItem.  # noqa: E501
        :type start_date: str
        :param food_attributes: The food_attributes of this SurveyFoodItem.  # noqa: E501
        :type food_attributes: List[FoodAttribute]
        :param food_portions: The food_portions of this SurveyFoodItem.  # noqa: E501
        :type food_portions: List[FoodPortion]
        :param input_foods: The input_foods of this SurveyFoodItem.  # noqa: E501
        :type input_foods: List[InputFoodSurvey]
        :param wweia_food_category: The wweia_food_category of this SurveyFoodItem.  # noqa: E501
        :type wweia_food_category: WweiaFoodCategory
        """
        self.swagger_types = {
            'fdc_id': int,
            'datatype': str,
            'description': str,
            'end_date': str,
            'food_class': str,
            'food_code': str,
            'publication_date': str,
            'start_date': str,
            'food_attributes': List[FoodAttribute],
            'food_portions': List[FoodPortion],
            'input_foods': List[InputFoodSurvey],
            'wweia_food_category': WweiaFoodCategory
        }

        self.attribute_map = {
            'fdc_id': 'fdcId',
            'datatype': 'datatype',
            'description': 'description',
            'end_date': 'endDate',
            'food_class': 'foodClass',
            'food_code': 'foodCode',
            'publication_date': 'publicationDate',
            'start_date': 'startDate',
            'food_attributes': 'foodAttributes',
            'food_portions': 'foodPortions',
            'input_foods': 'inputFoods',
            'wweia_food_category': 'wweiaFoodCategory'
        }
        self._fdc_id = fdc_id
        self._datatype = datatype
        self._description = description
        self._end_date = end_date
        self._food_class = food_class
        self._food_code = food_code
        self._publication_date = publication_date
        self._start_date = start_date
        self._food_attributes = food_attributes
        self._food_portions = food_portions
        self._input_foods = input_foods
        self._wweia_food_category = wweia_food_category

    @classmethod
    def from_dict(cls, dikt) -> 'SurveyFoodItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SurveyFoodItem of this SurveyFoodItem.  # noqa: E501
        :rtype: SurveyFoodItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fdc_id(self) -> int:
        """Gets the fdc_id of this SurveyFoodItem.


        :return: The fdc_id of this SurveyFoodItem.
        :rtype: int
        """
        return self._fdc_id

    @fdc_id.setter
    def fdc_id(self, fdc_id: int):
        """Sets the fdc_id of this SurveyFoodItem.


        :param fdc_id: The fdc_id of this SurveyFoodItem.
        :type fdc_id: int
        """
        if fdc_id is None:
            raise ValueError("Invalid value for `fdc_id`, must not be `None`")  # noqa: E501

        self._fdc_id = fdc_id

    @property
    def datatype(self) -> str:
        """Gets the datatype of this SurveyFoodItem.


        :return: The datatype of this SurveyFoodItem.
        :rtype: str
        """
        return self._datatype

    @datatype.setter
    def datatype(self, datatype: str):
        """Sets the datatype of this SurveyFoodItem.


        :param datatype: The datatype of this SurveyFoodItem.
        :type datatype: str
        """

        self._datatype = datatype

    @property
    def description(self) -> str:
        """Gets the description of this SurveyFoodItem.


        :return: The description of this SurveyFoodItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this SurveyFoodItem.


        :param description: The description of this SurveyFoodItem.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def end_date(self) -> str:
        """Gets the end_date of this SurveyFoodItem.


        :return: The end_date of this SurveyFoodItem.
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: str):
        """Sets the end_date of this SurveyFoodItem.


        :param end_date: The end_date of this SurveyFoodItem.
        :type end_date: str
        """

        self._end_date = end_date

    @property
    def food_class(self) -> str:
        """Gets the food_class of this SurveyFoodItem.


        :return: The food_class of this SurveyFoodItem.
        :rtype: str
        """
        return self._food_class

    @food_class.setter
    def food_class(self, food_class: str):
        """Sets the food_class of this SurveyFoodItem.


        :param food_class: The food_class of this SurveyFoodItem.
        :type food_class: str
        """

        self._food_class = food_class

    @property
    def food_code(self) -> str:
        """Gets the food_code of this SurveyFoodItem.


        :return: The food_code of this SurveyFoodItem.
        :rtype: str
        """
        return self._food_code

    @food_code.setter
    def food_code(self, food_code: str):
        """Sets the food_code of this SurveyFoodItem.


        :param food_code: The food_code of this SurveyFoodItem.
        :type food_code: str
        """

        self._food_code = food_code

    @property
    def publication_date(self) -> str:
        """Gets the publication_date of this SurveyFoodItem.


        :return: The publication_date of this SurveyFoodItem.
        :rtype: str
        """
        return self._publication_date

    @publication_date.setter
    def publication_date(self, publication_date: str):
        """Sets the publication_date of this SurveyFoodItem.


        :param publication_date: The publication_date of this SurveyFoodItem.
        :type publication_date: str
        """

        self._publication_date = publication_date

    @property
    def start_date(self) -> str:
        """Gets the start_date of this SurveyFoodItem.


        :return: The start_date of this SurveyFoodItem.
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: str):
        """Sets the start_date of this SurveyFoodItem.


        :param start_date: The start_date of this SurveyFoodItem.
        :type start_date: str
        """

        self._start_date = start_date

    @property
    def food_attributes(self) -> List[FoodAttribute]:
        """Gets the food_attributes of this SurveyFoodItem.


        :return: The food_attributes of this SurveyFoodItem.
        :rtype: List[FoodAttribute]
        """
        return self._food_attributes

    @food_attributes.setter
    def food_attributes(self, food_attributes: List[FoodAttribute]):
        """Sets the food_attributes of this SurveyFoodItem.


        :param food_attributes: The food_attributes of this SurveyFoodItem.
        :type food_attributes: List[FoodAttribute]
        """

        self._food_attributes = food_attributes

    @property
    def food_portions(self) -> List[FoodPortion]:
        """Gets the food_portions of this SurveyFoodItem.


        :return: The food_portions of this SurveyFoodItem.
        :rtype: List[FoodPortion]
        """
        return self._food_portions

    @food_portions.setter
    def food_portions(self, food_portions: List[FoodPortion]):
        """Sets the food_portions of this SurveyFoodItem.


        :param food_portions: The food_portions of this SurveyFoodItem.
        :type food_portions: List[FoodPortion]
        """

        self._food_portions = food_portions

    @property
    def input_foods(self) -> List[InputFoodSurvey]:
        """Gets the input_foods of this SurveyFoodItem.


        :return: The input_foods of this SurveyFoodItem.
        :rtype: List[InputFoodSurvey]
        """
        return self._input_foods

    @input_foods.setter
    def input_foods(self, input_foods: List[InputFoodSurvey]):
        """Sets the input_foods of this SurveyFoodItem.


        :param input_foods: The input_foods of this SurveyFoodItem.
        :type input_foods: List[InputFoodSurvey]
        """

        self._input_foods = input_foods

    @property
    def wweia_food_category(self) -> WweiaFoodCategory:
        """Gets the wweia_food_category of this SurveyFoodItem.


        :return: The wweia_food_category of this SurveyFoodItem.
        :rtype: WweiaFoodCategory
        """
        return self._wweia_food_category

    @wweia_food_category.setter
    def wweia_food_category(self, wweia_food_category: WweiaFoodCategory):
        """Sets the wweia_food_category of this SurveyFoodItem.


        :param wweia_food_category: The wweia_food_category of this SurveyFoodItem.
        :type wweia_food_category: WweiaFoodCategory
        """

        self._wweia_food_category = wweia_food_category
