# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI import util


class AbridgedFoodNutrient(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, number: int=None, name: str=None, amount: float=None, unit_name: str=None, derivation_code: str=None, derivation_description: str=None):  # noqa: E501
        """AbridgedFoodNutrient - a model defined in Swagger

        :param number: The number of this AbridgedFoodNutrient.  # noqa: E501
        :type number: int
        :param name: The name of this AbridgedFoodNutrient.  # noqa: E501
        :type name: str
        :param amount: The amount of this AbridgedFoodNutrient.  # noqa: E501
        :type amount: float
        :param unit_name: The unit_name of this AbridgedFoodNutrient.  # noqa: E501
        :type unit_name: str
        :param derivation_code: The derivation_code of this AbridgedFoodNutrient.  # noqa: E501
        :type derivation_code: str
        :param derivation_description: The derivation_description of this AbridgedFoodNutrient.  # noqa: E501
        :type derivation_description: str
        """
        self.swagger_types = {
            'number': int,
            'name': str,
            'amount': float,
            'unit_name': str,
            'derivation_code': str,
            'derivation_description': str
        }

        self.attribute_map = {
            'number': 'number',
            'name': 'name',
            'amount': 'amount',
            'unit_name': 'unitName',
            'derivation_code': 'derivationCode',
            'derivation_description': 'derivationDescription'
        }
        self._number = number
        self._name = name
        self._amount = amount
        self._unit_name = unit_name
        self._derivation_code = derivation_code
        self._derivation_description = derivation_description

    @classmethod
    def from_dict(cls, dikt) -> 'AbridgedFoodNutrient':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AbridgedFoodNutrient of this AbridgedFoodNutrient.  # noqa: E501
        :rtype: AbridgedFoodNutrient
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number(self) -> int:
        """Gets the number of this AbridgedFoodNutrient.


        :return: The number of this AbridgedFoodNutrient.
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number: int):
        """Sets the number of this AbridgedFoodNutrient.


        :param number: The number of this AbridgedFoodNutrient.
        :type number: int
        """

        self._number = number

    @property
    def name(self) -> str:
        """Gets the name of this AbridgedFoodNutrient.


        :return: The name of this AbridgedFoodNutrient.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AbridgedFoodNutrient.


        :param name: The name of this AbridgedFoodNutrient.
        :type name: str
        """

        self._name = name

    @property
    def amount(self) -> float:
        """Gets the amount of this AbridgedFoodNutrient.


        :return: The amount of this AbridgedFoodNutrient.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this AbridgedFoodNutrient.


        :param amount: The amount of this AbridgedFoodNutrient.
        :type amount: float
        """

        self._amount = amount

    @property
    def unit_name(self) -> str:
        """Gets the unit_name of this AbridgedFoodNutrient.


        :return: The unit_name of this AbridgedFoodNutrient.
        :rtype: str
        """
        return self._unit_name

    @unit_name.setter
    def unit_name(self, unit_name: str):
        """Sets the unit_name of this AbridgedFoodNutrient.


        :param unit_name: The unit_name of this AbridgedFoodNutrient.
        :type unit_name: str
        """

        self._unit_name = unit_name

    @property
    def derivation_code(self) -> str:
        """Gets the derivation_code of this AbridgedFoodNutrient.


        :return: The derivation_code of this AbridgedFoodNutrient.
        :rtype: str
        """
        return self._derivation_code

    @derivation_code.setter
    def derivation_code(self, derivation_code: str):
        """Sets the derivation_code of this AbridgedFoodNutrient.


        :param derivation_code: The derivation_code of this AbridgedFoodNutrient.
        :type derivation_code: str
        """

        self._derivation_code = derivation_code

    @property
    def derivation_description(self) -> str:
        """Gets the derivation_description of this AbridgedFoodNutrient.


        :return: The derivation_description of this AbridgedFoodNutrient.
        :rtype: str
        """
        return self._derivation_description

    @derivation_description.setter
    def derivation_description(self, derivation_description: str):
        """Sets the derivation_description of this AbridgedFoodNutrient.


        :param derivation_description: The derivation_description of this AbridgedFoodNutrient.
        :type derivation_description: str
        """

        self._derivation_description = derivation_description
