# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI.models.food_nutrient_source import FoodNutrientSource  # noqa: F401,E501
from FoodCentralAPI import util


class FoodNutrientDerivation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, code: str=None, description: str=None, food_nutrient_source: FoodNutrientSource=None):  # noqa: E501
        """FoodNutrientDerivation - a model defined in Swagger

        :param id: The id of this FoodNutrientDerivation.  # noqa: E501
        :type id: int
        :param code: The code of this FoodNutrientDerivation.  # noqa: E501
        :type code: str
        :param description: The description of this FoodNutrientDerivation.  # noqa: E501
        :type description: str
        :param food_nutrient_source: The food_nutrient_source of this FoodNutrientDerivation.  # noqa: E501
        :type food_nutrient_source: FoodNutrientSource
        """
        self.swagger_types = {
            'id': int,
            'code': str,
            'description': str,
            'food_nutrient_source': FoodNutrientSource
        }

        self.attribute_map = {
            'id': 'id',
            'code': 'code',
            'description': 'description',
            'food_nutrient_source': 'foodNutrientSource'
        }
        self._id = id
        self._code = code
        self._description = description
        self._food_nutrient_source = food_nutrient_source

    @classmethod
    def from_dict(cls, dikt) -> 'FoodNutrientDerivation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FoodNutrientDerivation of this FoodNutrientDerivation.  # noqa: E501
        :rtype: FoodNutrientDerivation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this FoodNutrientDerivation.


        :return: The id of this FoodNutrientDerivation.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this FoodNutrientDerivation.


        :param id: The id of this FoodNutrientDerivation.
        :type id: int
        """

        self._id = id

    @property
    def code(self) -> str:
        """Gets the code of this FoodNutrientDerivation.


        :return: The code of this FoodNutrientDerivation.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this FoodNutrientDerivation.


        :param code: The code of this FoodNutrientDerivation.
        :type code: str
        """

        self._code = code

    @property
    def description(self) -> str:
        """Gets the description of this FoodNutrientDerivation.


        :return: The description of this FoodNutrientDerivation.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this FoodNutrientDerivation.


        :param description: The description of this FoodNutrientDerivation.
        :type description: str
        """

        self._description = description

    @property
    def food_nutrient_source(self) -> FoodNutrientSource:
        """Gets the food_nutrient_source of this FoodNutrientDerivation.


        :return: The food_nutrient_source of this FoodNutrientDerivation.
        :rtype: FoodNutrientSource
        """
        return self._food_nutrient_source

    @food_nutrient_source.setter
    def food_nutrient_source(self, food_nutrient_source: FoodNutrientSource):
        """Sets the food_nutrient_source of this FoodNutrientDerivation.


        :param food_nutrient_source: The food_nutrient_source of this FoodNutrientDerivation.
        :type food_nutrient_source: FoodNutrientSource
        """

        self._food_nutrient_source = food_nutrient_source
