# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI import util


class FoodNutrientSource(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, code: str=None, description: str=None):  # noqa: E501
        """FoodNutrientSource - a model defined in Swagger

        :param id: The id of this FoodNutrientSource.  # noqa: E501
        :type id: int
        :param code: The code of this FoodNutrientSource.  # noqa: E501
        :type code: str
        :param description: The description of this FoodNutrientSource.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'id': int,
            'code': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'code': 'code',
            'description': 'description'
        }
        self._id = id
        self._code = code
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'FoodNutrientSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FoodNutrientSource of this FoodNutrientSource.  # noqa: E501
        :rtype: FoodNutrientSource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this FoodNutrientSource.


        :return: The id of this FoodNutrientSource.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this FoodNutrientSource.


        :param id: The id of this FoodNutrientSource.
        :type id: int
        """

        self._id = id

    @property
    def code(self) -> str:
        """Gets the code of this FoodNutrientSource.


        :return: The code of this FoodNutrientSource.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this FoodNutrientSource.


        :param code: The code of this FoodNutrientSource.
        :type code: str
        """

        self._code = code

    @property
    def description(self) -> str:
        """Gets the description of this FoodNutrientSource.


        :return: The description of this FoodNutrientSource.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this FoodNutrientSource.


        :param description: The description of this FoodNutrientSource.
        :type description: str
        """

        self._description = description
