# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI.models.nutrient_acquisition_details import NutrientAcquisitionDetails  # noqa: F401,E501
from FoodCentralAPI import util


class NutrientAnalysisDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sub_sample_id: int=None, amount: float=None, nutrient_id: int=None, lab_method_description: str=None, lab_method_original_description: str=None, lab_method_link: str=None, lab_method_technique: str=None, nutrient_acquisition_details: List[NutrientAcquisitionDetails]=None):  # noqa: E501
        """NutrientAnalysisDetails - a model defined in Swagger

        :param sub_sample_id: The sub_sample_id of this NutrientAnalysisDetails.  # noqa: E501
        :type sub_sample_id: int
        :param amount: The amount of this NutrientAnalysisDetails.  # noqa: E501
        :type amount: float
        :param nutrient_id: The nutrient_id of this NutrientAnalysisDetails.  # noqa: E501
        :type nutrient_id: int
        :param lab_method_description: The lab_method_description of this NutrientAnalysisDetails.  # noqa: E501
        :type lab_method_description: str
        :param lab_method_original_description: The lab_method_original_description of this NutrientAnalysisDetails.  # noqa: E501
        :type lab_method_original_description: str
        :param lab_method_link: The lab_method_link of this NutrientAnalysisDetails.  # noqa: E501
        :type lab_method_link: str
        :param lab_method_technique: The lab_method_technique of this NutrientAnalysisDetails.  # noqa: E501
        :type lab_method_technique: str
        :param nutrient_acquisition_details: The nutrient_acquisition_details of this NutrientAnalysisDetails.  # noqa: E501
        :type nutrient_acquisition_details: List[NutrientAcquisitionDetails]
        """
        self.swagger_types = {
            'sub_sample_id': int,
            'amount': float,
            'nutrient_id': int,
            'lab_method_description': str,
            'lab_method_original_description': str,
            'lab_method_link': str,
            'lab_method_technique': str,
            'nutrient_acquisition_details': List[NutrientAcquisitionDetails]
        }

        self.attribute_map = {
            'sub_sample_id': 'subSampleId',
            'amount': 'amount',
            'nutrient_id': 'nutrientId',
            'lab_method_description': 'labMethodDescription',
            'lab_method_original_description': 'labMethodOriginalDescription',
            'lab_method_link': 'labMethodLink',
            'lab_method_technique': 'labMethodTechnique',
            'nutrient_acquisition_details': 'nutrientAcquisitionDetails'
        }
        self._sub_sample_id = sub_sample_id
        self._amount = amount
        self._nutrient_id = nutrient_id
        self._lab_method_description = lab_method_description
        self._lab_method_original_description = lab_method_original_description
        self._lab_method_link = lab_method_link
        self._lab_method_technique = lab_method_technique
        self._nutrient_acquisition_details = nutrient_acquisition_details

    @classmethod
    def from_dict(cls, dikt) -> 'NutrientAnalysisDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NutrientAnalysisDetails of this NutrientAnalysisDetails.  # noqa: E501
        :rtype: NutrientAnalysisDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sub_sample_id(self) -> int:
        """Gets the sub_sample_id of this NutrientAnalysisDetails.


        :return: The sub_sample_id of this NutrientAnalysisDetails.
        :rtype: int
        """
        return self._sub_sample_id

    @sub_sample_id.setter
    def sub_sample_id(self, sub_sample_id: int):
        """Sets the sub_sample_id of this NutrientAnalysisDetails.


        :param sub_sample_id: The sub_sample_id of this NutrientAnalysisDetails.
        :type sub_sample_id: int
        """

        self._sub_sample_id = sub_sample_id

    @property
    def amount(self) -> float:
        """Gets the amount of this NutrientAnalysisDetails.


        :return: The amount of this NutrientAnalysisDetails.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this NutrientAnalysisDetails.


        :param amount: The amount of this NutrientAnalysisDetails.
        :type amount: float
        """

        self._amount = amount

    @property
    def nutrient_id(self) -> int:
        """Gets the nutrient_id of this NutrientAnalysisDetails.


        :return: The nutrient_id of this NutrientAnalysisDetails.
        :rtype: int
        """
        return self._nutrient_id

    @nutrient_id.setter
    def nutrient_id(self, nutrient_id: int):
        """Sets the nutrient_id of this NutrientAnalysisDetails.


        :param nutrient_id: The nutrient_id of this NutrientAnalysisDetails.
        :type nutrient_id: int
        """

        self._nutrient_id = nutrient_id

    @property
    def lab_method_description(self) -> str:
        """Gets the lab_method_description of this NutrientAnalysisDetails.


        :return: The lab_method_description of this NutrientAnalysisDetails.
        :rtype: str
        """
        return self._lab_method_description

    @lab_method_description.setter
    def lab_method_description(self, lab_method_description: str):
        """Sets the lab_method_description of this NutrientAnalysisDetails.


        :param lab_method_description: The lab_method_description of this NutrientAnalysisDetails.
        :type lab_method_description: str
        """

        self._lab_method_description = lab_method_description

    @property
    def lab_method_original_description(self) -> str:
        """Gets the lab_method_original_description of this NutrientAnalysisDetails.


        :return: The lab_method_original_description of this NutrientAnalysisDetails.
        :rtype: str
        """
        return self._lab_method_original_description

    @lab_method_original_description.setter
    def lab_method_original_description(self, lab_method_original_description: str):
        """Sets the lab_method_original_description of this NutrientAnalysisDetails.


        :param lab_method_original_description: The lab_method_original_description of this NutrientAnalysisDetails.
        :type lab_method_original_description: str
        """

        self._lab_method_original_description = lab_method_original_description

    @property
    def lab_method_link(self) -> str:
        """Gets the lab_method_link of this NutrientAnalysisDetails.


        :return: The lab_method_link of this NutrientAnalysisDetails.
        :rtype: str
        """
        return self._lab_method_link

    @lab_method_link.setter
    def lab_method_link(self, lab_method_link: str):
        """Sets the lab_method_link of this NutrientAnalysisDetails.


        :param lab_method_link: The lab_method_link of this NutrientAnalysisDetails.
        :type lab_method_link: str
        """

        self._lab_method_link = lab_method_link

    @property
    def lab_method_technique(self) -> str:
        """Gets the lab_method_technique of this NutrientAnalysisDetails.


        :return: The lab_method_technique of this NutrientAnalysisDetails.
        :rtype: str
        """
        return self._lab_method_technique

    @lab_method_technique.setter
    def lab_method_technique(self, lab_method_technique: str):
        """Sets the lab_method_technique of this NutrientAnalysisDetails.


        :param lab_method_technique: The lab_method_technique of this NutrientAnalysisDetails.
        :type lab_method_technique: str
        """

        self._lab_method_technique = lab_method_technique

    @property
    def nutrient_acquisition_details(self) -> List[NutrientAcquisitionDetails]:
        """Gets the nutrient_acquisition_details of this NutrientAnalysisDetails.


        :return: The nutrient_acquisition_details of this NutrientAnalysisDetails.
        :rtype: List[NutrientAcquisitionDetails]
        """
        return self._nutrient_acquisition_details

    @nutrient_acquisition_details.setter
    def nutrient_acquisition_details(self, nutrient_acquisition_details: List[NutrientAcquisitionDetails]):
        """Sets the nutrient_acquisition_details of this NutrientAnalysisDetails.


        :param nutrient_acquisition_details: The nutrient_acquisition_details of this NutrientAnalysisDetails.
        :type nutrient_acquisition_details: List[NutrientAcquisitionDetails]
        """

        self._nutrient_acquisition_details = nutrient_acquisition_details
