# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from FoodCentralAPI.models.base_model_ import Model
from FoodCentralAPI import util


class WweiaFoodCategory(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, wweia_food_category_code: int=None, wweia_food_category_description: str=None):  # noqa: E501
        """WweiaFoodCategory - a model defined in Swagger

        :param wweia_food_category_code: The wweia_food_category_code of this WweiaFoodCategory.  # noqa: E501
        :type wweia_food_category_code: int
        :param wweia_food_category_description: The wweia_food_category_description of this WweiaFoodCategory.  # noqa: E501
        :type wweia_food_category_description: str
        """
        self.swagger_types = {
            'wweia_food_category_code': int,
            'wweia_food_category_description': str
        }

        self.attribute_map = {
            'wweia_food_category_code': 'wweiaFoodCategoryCode',
            'wweia_food_category_description': 'wweiaFoodCategoryDescription'
        }
        self._wweia_food_category_code = wweia_food_category_code
        self._wweia_food_category_description = wweia_food_category_description

    @classmethod
    def from_dict(cls, dikt) -> 'WweiaFoodCategory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WweiaFoodCategory of this WweiaFoodCategory.  # noqa: E501
        :rtype: WweiaFoodCategory
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wweia_food_category_code(self) -> int:
        """Gets the wweia_food_category_code of this WweiaFoodCategory.


        :return: The wweia_food_category_code of this WweiaFoodCategory.
        :rtype: int
        """
        return self._wweia_food_category_code

    @wweia_food_category_code.setter
    def wweia_food_category_code(self, wweia_food_category_code: int):
        """Sets the wweia_food_category_code of this WweiaFoodCategory.


        :param wweia_food_category_code: The wweia_food_category_code of this WweiaFoodCategory.
        :type wweia_food_category_code: int
        """

        self._wweia_food_category_code = wweia_food_category_code

    @property
    def wweia_food_category_description(self) -> str:
        """Gets the wweia_food_category_description of this WweiaFoodCategory.


        :return: The wweia_food_category_description of this WweiaFoodCategory.
        :rtype: str
        """
        return self._wweia_food_category_description

    @wweia_food_category_description.setter
    def wweia_food_category_description(self, wweia_food_category_description: str):
        """Sets the wweia_food_category_description of this WweiaFoodCategory.


        :param wweia_food_category_description: The wweia_food_category_description of this WweiaFoodCategory.
        :type wweia_food_category_description: str
        """

        self._wweia_food_category_description = wweia_food_category_description
